"""Configuração inicial

Revision ID: 63cd43d83ec6
Revises: 
Create Date: 2025-01-20 22:59:05.881801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63cd43d83ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cultura', sa.String(length=50), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('previsao_plantio', sa.Date(), nullable=False),
    sa.Column('previsao_colheita', sa.Date(), nullable=False),
    sa.Column('produtividade_estimada', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('informacao_solo', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('informacao_solo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.drop_table('safras')
    # ### end Alembic commands ###
