version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agrolink
      - SECRET_KEY=chave_secreta_para_desenvolvimento
      - JWT_SECRET_KEY=chave_jwt_para_desenvolvimento
      - JWT_ACCESS_TOKEN_EXPIRES=86400
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=agrolink
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always

volumes:
  postgres_data: 